{
  SUPABASE_URL: "https://zbjyddsnemjgssnwmipv.supabase.co",
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpianlkZHNuZW1qZ3NzbndtaXB2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODE1NzczMTMsImV4cCI6MTk5NzE1MzMxM30._NskY5SW9wxG9oBXBsNxhcXkB9TRJQO6KPePtQPP83U",
}
